### ISSUE TITLE
Sculk cake causing Client sided chunk soft ban. 

### ISSUE THREAD

**Issue by Zunwolf1896** [MincraftEinstein/JustMoreCakes#13] opened 2023-12-01 08:48 UTC
MC: 1.20.1
Fabric: 0.14.23
jmc: 1.13.1

Player placed Sculk cake down, another player tpd to the area and got banned with the attached crash log. I tried to change the block to air using MC commands. It said "block changed" so I tp'd there to see if I could figure out what happened and got banned as well. 

Two of my staff managed to remove the cake usign world edit commands, and the player is now able to get in. 

Original Players Log: https://mclo.gs/mMw5uGs

My log: https://mclo.gs/DMDTGg2

**Comment by MincraftEinstein** [comment] 2023-12-02 00:08
Hi.
Thanks for reporting this!

I have done some testing and figured out that it is an incompatibility with Supplementaries caused by a missing block state on Supplementaries auto generated double sculk cake. This should be the only cake to cause problems with Supplementaries. I will try to have this fixed in the next update or two until then just make sure everyone on the server knows not to try to stack sculk cakes

**Comment by MincraftEinstein** [comment] 2023-12-02 03:03
![](https://github.trello.services/images/mini-trello-icon.png) [Crash with Sculk Cake caused by missing block state on Supplementaries double cake](https://trello.com/c/45l9TUuU/214-crash-caused-by-missing-block-state-on-supplementaries-double-cake)

**Closed as completed** 2024-03-05 23:27 UTC
